import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // DSS Design System Colors
        dss: {
          // Gray Scale
          gray: {
            50: "var(--dss-gray-50)",
            100: "var(--dss-gray-100)",
            200: "var(--dss-gray-200)",
            300: "var(--dss-gray-300)",
            400: "var(--dss-gray-400)",
            500: "var(--dss-gray-500)",
            600: "var(--dss-gray-600)",
            700: "var(--dss-gray-700)",
            800: "var(--dss-gray-800)",
            900: "var(--dss-gray-900)",
            950: "var(--dss-gray-950)",
          },
          // Brand Colors
          hub: {
            50: "var(--dss-hub-50)",
            100: "var(--dss-hub-100)",
            200: "var(--dss-hub-200)",
            300: "var(--dss-hub-300)",
            400: "var(--dss-hub-400)",
            500: "var(--dss-hub-500)",
            600: "var(--dss-hub-600)",
            700: "var(--dss-hub-700)",
            800: "var(--dss-hub-800)",
            900: "var(--dss-hub-900)",
            950: "var(--dss-hub-950)",
          },
          water: {
            50: "var(--dss-water-50)",
            100: "var(--dss-water-100)",
            200: "var(--dss-water-200)",
            300: "var(--dss-water-300)",
            400: "var(--dss-water-400)",
            500: "var(--dss-water-500)",
            600: "var(--dss-water-600)",
            700: "var(--dss-water-700)",
            800: "var(--dss-water-800)",
            900: "var(--dss-water-900)",
            950: "var(--dss-water-950)",
          },
          waste: {
            50: "var(--dss-waste-50)",
            100: "var(--dss-waste-100)",
            200: "var(--dss-waste-200)",
            300: "var(--dss-waste-300)",
            400: "var(--dss-waste-400)",
            500: "var(--dss-waste-500)",
            600: "var(--dss-waste-600)",
            700: "var(--dss-waste-700)",
            800: "var(--dss-waste-800)",
            900: "var(--dss-waste-900)",
            950: "var(--dss-waste-950)",
          },
          // Semantic Colors
          primary: {
            DEFAULT: "var(--dss-primary)",
            light: "var(--dss-primary-light)",
            disable: "var(--dss-primary-disable)",
            hover: "var(--dss-primary-hover)",
            deep: "var(--dss-primary-deep)",
            focus: "var(--dss-primary-focus)",
          },
          secondary: {
            DEFAULT: "var(--dss-secondary)",
            light: "var(--dss-secondary-light)",
            disable: "var(--dss-secondary-disable)",
            hover: "var(--dss-secondary-hover)",
            deep: "var(--dss-secondary-deep)",
            focus: "var(--dss-secondary-focus)",
          },
          tertiary: {
            DEFAULT: "var(--dss-tertiary)",
            light: "var(--dss-tertiary-light)",
            disable: "var(--dss-tertiary-disable)",
            hover: "var(--dss-tertiary-hover)",
            deep: "var(--dss-tertiary-deep)",
            focus: "var(--dss-tertiary-focus)",
          },
          accent: {
            DEFAULT: "var(--dss-accent)",
            light: "var(--dss-accent-light)",
            disable: "var(--dss-accent-disable)",
            hover: "var(--dss-accent-hover)",
            deep: "var(--dss-accent-deep)",
            focus: "var(--dss-accent-focus)",
          },
          dark: {
            DEFAULT: "var(--dss-dark)",
            light: "var(--dss-dark-light)",
            disable: "var(--dss-dark-disable)",
            hover: "var(--dss-dark-hover)",
            deep: "var(--dss-dark-deep)",
            focus: "var(--dss-dark-focus)",
          },
          // Feedback Colors
          positive: {
            DEFAULT: "var(--dss-positive)",
            light: "var(--dss-positive-light)",
            disable: "var(--dss-positive-disable)",
            hover: "var(--dss-positive-hover)",
            deep: "var(--dss-positive-deep)",
          },
          negative: {
            DEFAULT: "var(--dss-negative)",
            light: "var(--dss-negative-light)",
            disable: "var(--dss-negative-disable)",
            hover: "var(--dss-negative-hover)",
            deep: "var(--dss-negative-deep)",
          },
          warning: {
            DEFAULT: "var(--dss-warning)",
            light: "var(--dss-warning-light)",
            disable: "var(--dss-warning-disable)",
            hover: "var(--dss-warning-hover)",
            deep: "var(--dss-warning-deep)",
          },
          info: {
            DEFAULT: "var(--dss-info)",
            light: "var(--dss-info-light)",
            disable: "var(--dss-info-disable)",
            hover: "var(--dss-info-hover)",
            deep: "var(--dss-info-deep)",
          },
        },
      },
      spacing: {
        "dss-0": "var(--dss-spacing-0)",
        "dss-px": "var(--dss-spacing-px)",
        "dss-0.5": "var(--dss-spacing-0_5)",
        "dss-1": "var(--dss-spacing-1)",
        "dss-1.5": "var(--dss-spacing-1_5)",
        "dss-2": "var(--dss-spacing-2)",
        "dss-2.5": "var(--dss-spacing-2_5)",
        "dss-3": "var(--dss-spacing-3)",
        "dss-3.5": "var(--dss-spacing-3_5)",
        "dss-4": "var(--dss-spacing-4)",
        "dss-5": "var(--dss-spacing-5)",
        "dss-6": "var(--dss-spacing-6)",
        "dss-8": "var(--dss-spacing-8)",
        "dss-10": "var(--dss-spacing-10)",
        "dss-12": "var(--dss-spacing-12)",
        "dss-16": "var(--dss-spacing-16)",
        "dss-20": "var(--dss-spacing-20)",
        "dss-24": "var(--dss-spacing-24)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "dss-none": "var(--dss-radius-none)",
        "dss-sm": "var(--dss-radius-sm)",
        "dss-md": "var(--dss-radius-md)",
        "dss-lg": "var(--dss-radius-lg)",
        "dss-xl": "var(--dss-radius-xl)",
        "dss-2xl": "var(--dss-radius-2xl)",
        "dss-3xl": "var(--dss-radius-3xl)",
        "dss-full": "var(--dss-radius-full)",
      },
      boxShadow: {
        "dss-xs": "var(--dss-shadow-xs)",
        "dss-sm": "var(--dss-shadow-sm)",
        "dss-md": "var(--dss-shadow-md)",
        "dss-lg": "var(--dss-shadow-lg)",
        "dss-xl": "var(--dss-shadow-xl)",
        "dss-2xl": "var(--dss-shadow-2xl)",
        "dss-inner": "var(--dss-shadow-inner)",
        "dss-focus": "var(--dss-shadow-focus)",
        "dss-focus-error": "var(--dss-shadow-focus-error)",
        "dss-focus-success": "var(--dss-shadow-focus-success)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
